---
# tasks file for main
- name: Install a list of packages
  apt:
    pkg:
      - mc
      - python
      - git
      - docker.io
    update_cache: yes
    state: present

- name: Install docker-compose from official github repo
  get_url:
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 755

- name: Set authorized key took from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Allow root SSH access
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PermitRootLogin"
    line="PermitRootLogin yes"
    state=present

- name: Allow root password access
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp="^PasswordAuthentication"
    line="PasswordAuthentication yes"
    state=present

#- name: copy rsa key for ROOT
#  synchronize:
#    src: "~/.ssh/id_rsa"
#    dest: "/root/.ssh/id_rsa"

- name: Restart sshd
  service:
    name: sshd
    state: restarted
